[package]
name = "bevy-snake"
version = "0.1.0"
edition = "2021"
description = "SNAKE WITH GUNS!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# note: use these commands to build for web. you will need to add the assets folder and an index.html file for everything to work
# cargo build --release --target wasm32-unknown-unknown
# wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release/bevy-snake.wasm

[dependencies.bevy]
version = "0.7"
default-features = false
# These are the remaining default features other than `bevy_audio` and `mp3`
features = [
  "animation",
  "bevy_gilrs",
  "bevy_winit",
  "render",
  "png",
  "hdr",
  "x11",
  "filesystem_watcher",
]

[dependencies]
rand = "0.8.5"
bevy_kira_audio = "0.9.0"
bevy_egui = "0.14"
bevy-web-resizer = "2.0"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[package.metadata.bundle]